// /*
// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do
// not exceed four million, find the sum of the even-valued terms.
// */

// /*
// size: 40000000
// */
let sum = 0;
const evenNumbers = () => {
  for (let i = 0; i < 40; i++) {
    if (i % 2 !== 0) {
      perro = [i];
      sum += parseInt(perro);
      console.log(sum);
    }
  }
  return sum;
};
console.log(evenNumbers());
